name: Auto Run main.py

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 8:30 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies (if any)
      run: |
        pip install -r requirements.txt || true

    - name: Run script
      working-directory: angel_one_algo
      run: python main.py

