name: Run main.py daily and manually

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '55 3 * * *'  # runs daily at 3:55 AM UTC = 9:25 AM IST

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: angel_one_algo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
