name: Run main.py manually

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: angel_one_algo  # 👈 tells GitHub to run all steps from this folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # this now works because working directory is correct

      - name: Run main.py
        run: python main.py
